#!/bin/bash

pokemon_list=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
mkdir -p pokemon_data

for pokemon in "${pokemon_list[@]}"; do
   echo "Fetching data for $pokemon..."
   curl -s "https://pokeapi.co/api/v2/pokemon/$pokemon" -o "pokemon_data/$pokemon.json"
   echo "Saved data to pokemon_data/$pokemon.json ✅"
   sleep 1
done
